import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import type { DailyBillSummary } from "@/hooks/useDailyBill";
import { formatCurrency } from "./currency";

export const generateDailyBillPDF = async (
  dailyBills: DailyBillSummary[],
  elementId: string = "daily-bills-content"
) => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error("Element not found for PDF generation");
    }

    // Capture the element as canvas
    const canvas = await html2canvas(element, {
      scale: 2,
      backgroundColor: "#ffffff",
      useCORS: true,
      logging: false,
    });

    // Create PDF
    const pdf = new jsPDF({
      orientation: "landscape",
      unit: "mm",
      format: "a4",
    });

    const imgWidth = pdf.internal.pageSize.getWidth();
    const imgHeight = (canvas.height * imgWidth) / canvas.width;
    let heightLeft = imgHeight;
    let position = 0;

    // Add image to PDF
    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
    heightLeft -= pdf.internal.pageSize.getHeight();

    // Add multiple pages if needed
    while (heightLeft >= 0) {
      position = heightLeft - imgHeight;
      pdf.addPage();
      pdf.addImage(imgData, "PNG", 0, position, imgWidth, imgHeight);
      heightLeft -= pdf.internal.pageSize.getHeight();
    }

    // Generate filename with date
    const dateStr = new Date().toISOString().split("T")[0];
    const filename = `Daily-Bills-${dateStr}.pdf`;

    // Download PDF
    pdf.save(filename);
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw new Error("Failed to generate PDF");
  }
};

export const generateDetailedBillPDF = (
  dailyBills: DailyBillSummary[],
  companyName: string = "POKLEH ENTERPRISE"
) => {
  const pdf = new jsPDF({
    orientation: "landscape",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 12;
  const contentWidth = pageWidth - 2 * margin; // 273mm for A4 landscape
  let yPosition = margin;
  let pageNumber = 1;

  // Column definitions — full width (sum = 273mm)
  const cols = {
    supplier:  { x: margin,        w: 55 },
    product:   { x: margin + 55,   w: 50 },
    sold:      { x: margin + 105,  w: 22 },
    wasted:    { x: margin + 127,  w: 22 },
    reduction: { x: margin + 149,  w: 22 },
    payable:   { x: margin + 171,  w: 22 },
    cost:      { x: margin + 193,  w: 34 },
    amount:    { x: margin + 227,  w: 46 },
  };

  // Color palette
  const C_PRIMARY: [number, number, number] = [0, 51, 102];
  const C_HEADER_BG: [number, number, number] = [220, 235, 250];
  const C_SUBTOTAL_BG: [number, number, number] = [240, 245, 252];
  const C_GRAND_BG: [number, number, number] = [0, 51, 102];
  const C_TEXT: [number, number, number] = [0, 0, 0];
  const C_MUTED: [number, number, number] = [110, 110, 110];
  const C_ORANGE: [number, number, number] = [200, 100, 0];
  const C_GREEN: [number, number, number] = [0, 102, 0];
  const C_WHITE: [number, number, number] = [255, 255, 255];

  const addText = (
    text: string,
    x: number,
    y: number,
    fontSize = 10,
    fontStyle: "normal" | "bold" = "normal",
    color: [number, number, number] = C_TEXT,
    align: "left" | "right" | "center" = "left"
  ) => {
    pdf.setFont("helvetica", fontStyle);
    pdf.setFontSize(fontSize);
    pdf.setTextColor(...color);
    pdf.text(text, x, y, { align });
  };

  const drawRect = (x: number, y: number, w: number, h: number, fill: [number, number, number]) => {
    pdf.setFillColor(...fill);
    pdf.rect(x, y, w, h, "F");
  };

  const drawCell = (
    x: number,
    y: number,
    w: number,
    h: number,
    text: string,
    opts: {
      fontSize?: number;
      fontStyle?: "normal" | "bold";
      color?: [number, number, number];
      align?: "left" | "right" | "center";
      fill?: [number, number, number];
      padding?: number;
    } = {}
  ) => {
    const {
      fontSize = 8,
      fontStyle = "normal",
      color = C_TEXT,
      align = "left",
      fill,
      padding = 2,
    } = opts;
    if (fill) drawRect(x, y, w, h, fill);
    pdf.setFont("helvetica", fontStyle);
    pdf.setFontSize(fontSize);
    pdf.setTextColor(...color);
    const textX =
      align === "right" ? x + w - padding : align === "center" ? x + w / 2 : x + padding;
    pdf.text(text, textX, y + h - padding - 0.5, { align });
  };

  const drawHLine = (x1: number, x2: number, y: number, lineWidth = 0.1, color: [number, number, number] = [190, 190, 190]) => {
    pdf.setDrawColor(...color);
    pdf.setLineWidth(lineWidth);
    pdf.line(x1, y, x2, y);
  };

  const drawFooter = () => {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(7);
    pdf.setTextColor(...C_MUTED);
    pdf.text(`Generated by ${companyName} | Page ${pageNumber}`, margin, pageHeight - 5);
    pdf.text(new Date().toLocaleString(), pageWidth - margin, pageHeight - 5, { align: "right" });
  };

  const checkNewPage = (requiredHeight: number) => {
    if (yPosition + requiredHeight > pageHeight - margin - 8) {
      drawFooter();
      pdf.addPage();
      pageNumber++;
      yPosition = margin;
      addText(`${companyName} — Daily Bills Report (Continued)`, margin, yPosition, 10, "bold", C_PRIMARY);
      yPosition += 6;
      drawColumnHeader();
    }
  };

  const headerH = 6;
  const lineH = 5;

  const drawColumnHeader = () => {
    drawRect(margin, yPosition, contentWidth, headerH, C_PRIMARY);
    const headers: { c: typeof cols.supplier; text: string; align: "left" | "right" }[] = [
      { c: cols.supplier, text: "Supplier", align: "left" },
      { c: cols.product, text: "Product", align: "left" },
      { c: cols.sold, text: "Sold", align: "right" },
      { c: cols.wasted, text: "Wasted", align: "right" },
      { c: cols.reduction, text: "Reduction", align: "right" },
      { c: cols.payable, text: "Payable", align: "right" },
      { c: cols.cost, text: "Cost/Pax", align: "right" },
      { c: cols.amount, text: "Amount (RM)", align: "right" },
    ];
    headers.forEach((h) =>
      drawCell(h.c.x, yPosition, h.c.w, headerH, h.text, {
        fontSize: 7.5,
        fontStyle: "bold",
        color: C_WHITE,
        align: h.align,
      })
    );
    yPosition += headerH;
  };

  // === HEADER ===
  addText(companyName, margin, yPosition, 16, "bold", C_PRIMARY);
  yPosition += 7;
  addText("Daily Bills Report", margin, yPosition, 12, "bold");
  yPosition += 5;
  addText(`Generated: ${new Date().toLocaleString()}`, margin, yPosition, 8, "normal", C_MUTED);
  yPosition += 6;

  // === SUMMARY BOX ===
  const totalBills = dailyBills.length;
  const totalSold = dailyBills.reduce((s, b) => s + b.totalSold, 0);
  const totalWasted = dailyBills.reduce((s, b) => s + b.totalWasted, 0);
  const totalReduction = dailyBills.reduce((s, b) => s + b.totalReduction, 0);
  const totalPayable = dailyBills.reduce((s, b) => s + b.totalPayable, 0);
  const totalAmount = dailyBills.reduce((s, b) => s + b.totalAmount, 0);

  const summaryH = 14;
  drawRect(margin, yPosition, contentWidth, summaryH, C_HEADER_BG);
  pdf.setDrawColor(...C_PRIMARY);
  pdf.setLineWidth(0.3);
  pdf.rect(margin, yPosition, contentWidth, summaryH);

  const summaryCells = [
    { label: "Bills", value: String(totalBills), color: C_PRIMARY },
    { label: "Sold", value: String(totalSold), color: C_PRIMARY },
    { label: "Wasted", value: String(totalWasted), color: C_ORANGE },
    { label: "Payable Qty", value: String(totalPayable), color: C_PRIMARY },
    { label: "Amount Due", value: formatCurrency(totalAmount), color: C_GREEN },
  ];
  const cellW = contentWidth / summaryCells.length;
  summaryCells.forEach((cell, i) => {
    const cx = margin + i * cellW;
    if (i > 0) {
      pdf.setDrawColor(180, 200, 220);
      pdf.setLineWidth(0.2);
      pdf.line(cx, yPosition, cx, yPosition + summaryH);
    }
    addText(cell.label, cx + cellW / 2, yPosition + 4.5, 7, "normal", C_MUTED, "center");
    addText(cell.value, cx + cellW / 2, yPosition + 10.5, 9, "bold", cell.color, "center");
  });
  yPosition += summaryH + 5;

  // === TABLE ===
  drawColumnHeader();

  dailyBills.forEach((bill) => {
    // Bill section header
    checkNewPage(lineH + 1 + bill.lines.length * lineH + lineH + 1 + 3);
    drawRect(margin, yPosition, contentWidth, lineH + 1, C_HEADER_BG);
    addText(
      `${new Date(bill.date).toLocaleDateString()}  —  ${bill.truckName}`,
      margin + 2,
      yPosition + lineH - 0.3,
      9,
      "bold",
      C_PRIMARY
    );
    yPosition += lineH + 1;

    // Line rows
    bill.lines.forEach((line) => {
      checkNewPage(lineH);
      drawCell(cols.supplier.x, yPosition, cols.supplier.w, lineH, line.supplierName, { fontSize: 7.5 });
      drawCell(cols.product.x, yPosition, cols.product.w, lineH, line.productType, { fontSize: 7.5, fontStyle: "bold" });
      drawCell(cols.sold.x, yPosition, cols.sold.w, lineH, String(line.quantitySold), { fontSize: 7.5, align: "right" });
      drawCell(cols.wasted.x, yPosition, cols.wasted.w, lineH, String(line.quantityWasted), { fontSize: 7.5, align: "right", color: C_ORANGE });
      drawCell(cols.reduction.x, yPosition, cols.reduction.w, lineH, line.wastageReduction > 0 ? `-${line.wastageReduction}` : "—", { fontSize: 7.5, align: "right", color: C_GREEN });
      drawCell(cols.payable.x, yPosition, cols.payable.w, lineH, String(line.payableQuantity), { fontSize: 7.5, fontStyle: "bold", align: "right" });
      drawCell(cols.cost.x, yPosition, cols.cost.w, lineH, formatCurrency(line.costPerPax), { fontSize: 7.5, align: "right" });
      drawCell(cols.amount.x, yPosition, cols.amount.w, lineH, formatCurrency(line.payableAmount), { fontSize: 7.5, fontStyle: "bold", align: "right", color: C_GREEN });
      drawHLine(margin, margin + contentWidth, yPosition + lineH, 0.1);
      yPosition += lineH;
    });

    // Subtotal row
    drawRect(margin, yPosition, contentWidth, lineH + 1, C_SUBTOTAL_BG);
    const subLabelW = cols.product.x + cols.product.w - margin;
    drawCell(margin, yPosition, subLabelW, lineH + 1, `Subtotal — ${bill.truckName}`, { fontSize: 7.5, fontStyle: "bold", color: C_MUTED });
    drawCell(cols.sold.x, yPosition, cols.sold.w, lineH + 1, String(bill.totalSold), { fontSize: 7.5, fontStyle: "bold", align: "right" });
    drawCell(cols.wasted.x, yPosition, cols.wasted.w, lineH + 1, String(bill.totalWasted), { fontSize: 7.5, fontStyle: "bold", align: "right", color: C_ORANGE });
    drawCell(cols.reduction.x, yPosition, cols.reduction.w, lineH + 1, String(bill.totalReduction), { fontSize: 7.5, fontStyle: "bold", align: "right", color: C_GREEN });
    drawCell(cols.payable.x, yPosition, cols.payable.w, lineH + 1, String(bill.totalPayable), { fontSize: 7.5, fontStyle: "bold", align: "right" });
    drawCell(cols.amount.x, yPosition, cols.amount.w, lineH + 1, formatCurrency(bill.totalAmount), { fontSize: 8, fontStyle: "bold", align: "right", color: C_GREEN });
    yPosition += lineH + 1 + 3;
  });

  // === GRAND TOTAL ===
  checkNewPage(14);
  const grandH = 9;
  drawRect(margin, yPosition, contentWidth, grandH, C_GRAND_BG);
  const grandLabelW = cols.product.x + cols.product.w - margin;
  drawCell(margin, yPosition, grandLabelW, grandH, "GRAND TOTAL", { fontSize: 11, fontStyle: "bold", color: C_WHITE });
  drawCell(cols.sold.x, yPosition, cols.sold.w, grandH, String(totalSold), { fontSize: 9, fontStyle: "bold", color: C_WHITE, align: "right" });
  drawCell(cols.wasted.x, yPosition, cols.wasted.w, grandH, String(totalWasted), { fontSize: 9, fontStyle: "bold", color: C_WHITE, align: "right" });
  drawCell(cols.reduction.x, yPosition, cols.reduction.w, grandH, String(totalReduction), { fontSize: 9, fontStyle: "bold", color: C_WHITE, align: "right" });
  drawCell(cols.payable.x, yPosition, cols.payable.w, grandH, String(totalPayable), { fontSize: 9, fontStyle: "bold", color: C_WHITE, align: "right" });
  drawCell(cols.amount.x, yPosition, cols.amount.w, grandH, formatCurrency(totalAmount), { fontSize: 11, fontStyle: "bold", color: C_WHITE, align: "right" });
  yPosition += grandH + 4;

  // Amount due line
  addText(`AMOUNT DUE: ${formatCurrency(totalAmount)}`, margin + contentWidth, yPosition, 12, "bold", C_GREEN, "right");

  // === FOOTER (last page) ===
  drawFooter();

  // Save
  const dateStr = new Date().toISOString().split("T")[0];
  pdf.save(`Daily-Bills-${dateStr}.pdf`);
};
